# Generated by Django 5.0.6 on 2024-05-13 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('change', models.CharField(max_length=50)),
                ('thought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.thought')),
            ],
        ),
    ]
